---
title: "stats205_final_project"
output: pdf_document
date: "2024-06-04"
---

```{r}
library(rjags)
library(coda)
library(ggplot2)
library(dplyr)
library(rstan)
library(rstanarm)
library(bayesplot)
library(bayesrules)
library(tidybayes)
library(stringr)
```



```{r}
salaries=read.csv("salaries.csv")
df <- salaries %>%
  mutate(
    grouped_job_title = case_when(
      grepl("Machine Learning|ML", job_title) ~ "Machine Learning Engineer",
      grepl("Data Science|Data Scientist", job_title)~ "Data Scientist",
      grepl("Data Analyst|Data Analytics|Visualization", job_title)  ~ "Data Analyst",
      grepl("AI|Artificial Intelligence", job_title) ~ "AI Engineer",
      grepl("Business Intelligence|BI", job_title) ~ "Business Intelligence",
      grepl("Data Engineer", job_title) ~ "Data Engineer",
      TRUE ~ "Other"
    )
  )

df = df %>% filter(employee_residence %in% c("CA", "DE", "ES", "GB", "US"))
```

```{r}
unique(salaries %>%
  filter(str_detect(job_title, regex("AI", ignore_case = TRUE))) %>%
  select(job_title))
```


```{r}
# Histogram using ggplot2
ggplot(df, aes(x = salary_in_usd)) +
  geom_histogram(binwidth = 5000, fill = "grey", color = "black", alpha = 0.7) +
  labs(title = "Distribution of Salaries", x = "Salary in USD", y = "Frequency") +
  theme_minimal()
```
```{r}
df %>%
  filter(employee_residence %in% c("CA","US")) %>%
  summarise(mean_salary = mean(salary_in_usd, na.rm = TRUE)) %>%
  pull(mean_salary)
```


```{r}
# en = entry level, ex = intermediate, mi = mid level, se = senior
ggplot(df, aes(x=experience_level, y=salary_in_usd)) +
  geom_boxplot() +
  labs(title="Salary distribution by experience level",
       x="Experience Level",
       y="Salary in USD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(df, aes(x = factor(remote_ratio))) +
  geom_bar(fill = "gray") +
  theme_minimal() +
  labs(title = "Distribution of Remote Ratios", x = "Remote Ratio", y = "Count")
```

```{r}
ggplot(df, aes(x=factor(remote_ratio), y=salary_in_usd)) +
  geom_boxplot() +
  labs(title="Salary distribution by remote ratio",
       x="Remote ratio",
       y="Salary in USD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
ggplot(df, aes(x=grouped_job_title, y=salary_in_usd)) +
  geom_boxplot() +
  labs(title="Salary distribution by job title",
       x="Job Title",
       y="Salary in USD") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(df, aes(x=employee_residence, y=salary_in_usd)) +
  geom_boxplot() +
  labs(
    title="Salary distribution by country",
    x="Location",
    y="Salary in USD")
```
```{r}
N=dim(df)[1]
job=as.numeric(factor(df$grouped_job_title))
n_jobs=length(as.numeric(table(job)))
y=df$salary_in_usd
```

```{r}
y.bar.jobs = rep(0,n_jobs)
s2.jobs = rep(0,n_jobs)

for (i in 1:n_jobs){
  y.bar.jobs[i] <- mean(y[which(job==i)])
  s2.jobs[i] <- var(y[which(job==i)])
}

mean.y.bar.jobs<- mean(y.bar.jobs)
mean.s2.jobs <- mean(s2.jobs)
var.y.bar.jobs <- var(y.bar.jobs)

init.val <- list(
  mu=y.bar.jobs,
  precision=1/s2.jobs,
  mu_0=mean.y.bar.jobs,
  itau=1/var.y.bar.jobs
)

mu_0_sigma=1/1000000
tau_1=1
tau_2=2 / (1e-9)
sigma_1=1
sigma_2=2 / (1e-9)

data_list <- list('y' = y,
                  'N' = N,
                  'n_jobs' = n_jobs,
                  'job' = job,
                  'sigma_1'=sigma_1,
                  'sigma_2'=sigma_2,
                  'mu_0_sigma'=mu_0_sigma,
                  'tau_1'=tau_1,
                  'tau_2'=tau_2)
```


```{r}
jags <- jags.model('job_position_model.txt',
                   data=data_list,
                   inits=init.val,
                   n.chains=1)


jags.output.coda <- coda.samples(jags,c('tau', 'sigma', 'mu_0', 'mu'),10000)
s = summary(jags.output.coda)
s
```

```{r}
modeljob <- '
data {
  int<lower=0> N;  // Number of observations
  int<lower=1> K;  // Number of countries
  int<lower=1, upper=K> job[N];  // Country index for each observation
  real salary[N];  // Salary observations
}

parameters {
  vector[K] mu;  // Mean salary for each country
  vector<lower=0>[K] sigma;  // Standard deviation of salary for each country
  real<lower = 0> mu0;         // Hyperparameter for mu
  real<lower = 0> tau;         // Hyperparameter for sigma
}

model {
  for (i in 1:N)
    salary[i] ~ normal(mu[job[i]], sigma[job[i]]);
  mu ~ normal(mu0, tau);           // Prior for mu
  sigma ~ scaled_inv_chi_square(1, .05); // Prior for sigma
  mu0 ~ normal(0, 1000000);        // Hyperprior for mu0
  tau ~ scaled_inv_chi_square(1, .05);
}
'

N <- nrow(df)
K <- length(unique(df$grouped_job_title))
job <- as.numeric(factor(df$grouped_job_title))
salary <- df$salary_in_usd

modeljobmc <- stan(model_code =modeljob, data=list(N = N, K = K, job = job, salary = salary), iter = 5000*2, chains = 1)
summary(modeljobmc)
```


